repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7

  - repo: local
    hooks:
    - id: tests
      name: test
      entry: backend/manage.py
      language: system
      types: [python]
      args: [geo]